/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AssignCreating: typeof import('./components/AssignCreating.vue')['default']
    ExercisesCreating: typeof import('./components/ExercisesCreating.vue')['default']
    IndexPage: typeof import('./components/IndexPage.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    QuestionsCreating: typeof import('./components/QuestionsCreating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SurveyDetail: typeof import('./components/TheSurvey/SurveyDetail.vue')['default']
    TheHeader: typeof import('./components/Header/TheHeader.vue')['default']
    TheMenu: typeof import('./components/Menu/TheMenu.vue')['default']
  }
}
